apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: csup96/ticketing-auth
          env:
            - name: DB_HOST
              value: auth-db-svc
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: ticketing
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
